### ISSUE TITLE
добавить поля "телефон" и "мой город" в личном кабинете

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [nicolaypetrovich/rocket-prof-sys-tools#36]
http://prof-sys-tools.rocketcompany.website/my-account/edit-account/
http://prntscr.com/kzdf76
http://prntscr.com/kzdff7
Кроме того, не изменяется имя, почта после нажатия кнопки "сохранить"

**Comment by Mugenzo** [comment]
нужно верстальщику править валидацию форм

**Comment by VladyslavKovalchuk** [comment]
после изменения имени в форме и нажатия "сохранить", оно не изменяется и сохраняется, а только остается в форме
